name: ArtistLeonardo
favicon: null
layout_spectrum: 0.07685700012370944
typography_spectrum: 0.7333513621706516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09450350748375058
  lightness: 0.9949453286826611
  saturation: 0.6874939997214824
  rhythmicContrast: 0.6236105144489557
purpose: []
